the script can now save to manual path. It can only use full path for now.

diff --git a/daupd b/daupd
--- a/daupd
+++ b/daupd
@@ -22,35 +22,37 @@ echo -e "\nWhere do you want to save the script?"
 select place in "default" "manual"
 do 
   case $place in 
-    default ) path_to_save="~/scripts/docker_updates" 
-      if [-d $path_to_save]
-      then
-        echo "Saving to path..."
-      else 
-        echo "Creating path..."
-        mkdir $path_to_save || echo "Can't create path" ; exit;;
-      fi
-      break
-    manual ) read -p "Enter the path: " path_to_save
-      if [-d $path_to_save]
-      then
-        echo "Saving to path..."
-      else 
-        echo "Creating default path..."
-        mkdir $path_to_save
-      fi
-      break
+    default ) path_to_save="/home/$USER/scripts/docker_updates" ; break ;;
+    manual ) read -p "Enter the path (use full path): " path_to_save ; break ;;
   esac
 done
 
-echo -e "\nCreating script..."
+if [[ $place =~ "default" ]]
+then 
+  if [ -e "$path_to_save" ]
+  then
+    echo -e "\nSaving to default path ($path_to_save)..."
+  else 
+    echo -e "\nCreating default path ($path_to_save)..."
+    mkdir $path_to_save || echo "Can't create path" ; exit
+  fi
+else
+  if [ -e "$path_to_save" ]
+  then
+    echo -e "\nSaving to path..."
+  else 
+    echo -e "\nCreating path..."
+    mkdir $path_to_save || echo "Can't create path" ; exit
+  fi
+fi
+echo "Creating script..."
 # if [ -d ~/scripts/docker_updates ]
 # then 
 #   echo "Path exists"
 # else 
 #   echo "Path doesn't exist. Creating..."
 #   mkdir ~/scripts/docker_updates
-fi
+#fi
 echo -e "cd $compose_file_path\ndocker compose pull\ndocker compose up -d" > "$path_to_save"/"$name"_update.sh
 
 echo "Script ready"
@@ -61,7 +63,7 @@ select yn in "Yes" "No"
 do
   case $yn in
     Yes ) break;;
-    No ) exit;;
+    No ) echo "Done!" ; exit;;
   esac
 done 
 
